name: Build and push image variant

on:
  workflow_call:
    inputs:
      ARCHES:
        required: true
        type: string
      CUDA_VER:
        required: true
        type: string
      LINUX_VER:
        required: true
        type: string
      PYTHON_VER:
        required: true
        type: string
      TAG:
        required: true
        type: string

jobs:
  docker-build:
    strategy:
      matrix:
        ARCH: ${{ fromJSON(inputs.ARCHES) }}
        CUDA_VER: ["${{ inputs.CUDA_VER }}"]
        LINUX_VER: ["${{ inputs.LINUX_VER }}"]
        PYTHON_VER: ["${{ inputs.PYTHON_VER }}"]
      fail-fast: false
    runs-on: "linux-${{ matrix.ARCH }}-cpu4"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          endpoint: builders
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          build-args: |
            CUDA_VER=${{ inputs.CUDA_VER }}
            LINUX_VER=${{ inputs.LINUX_VER }}
            PYTHON_VER=${{ inputs.PYTHON_VER }}
          tags: ${{ inputs.TAG }}-${{ matrix.ARCH }}
